### ISSUE TITLE
Video thumbs are Showing

### ISSUE THREAD

**Issue by arunpk95** [GEC-Developers/Status-Saver#24]
![88cebd1d-5eb1-47c4-9bab-33ad5a296fad](https://user-images.githubusercontent.com/17641189/48971914-77051980-f046-11e8-9331-1614908ea904.jpg)
Video thumnail is shown only for Last Video 
Device Used: Redmi Note 3

**Comment by Rawkush** [comment]
try the app available in playstore and tell us here if that apk also contains this problem
https://play.google.com/store/apps/details?id=com.tripleastudio.whatsappstatussaver

**Comment by Rawkush** [comment]
closing due to insufficient information and no resposnse from you
